pipeline:
  backend-unit-tests:
    group: test
    image: python:3.7
    environment:
      TILDE_SQL_HOST: postgres
    commands:
      - cd backend
      - pip install --upgrade pip
      - pip install -r requirements.txt
      # - python manage.py migrate
      - python manage.py test

  frontend-unit-tests:
    group: test
    image: node:12
    commands:
      - cd frontend
      - npm install
      - npm test

  # frontend-deploy-prod:
  #   image: node:12
  #   commands:
  #     - cd frontend
  #     - ./deploy_prod.sh

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - "6543:5432"
