kind: pipeline
type: docker
name: default

steps:
  - name: frontend-deploy-staging
    image: google/cloud-sdk
    volumes:
      - name: secret_keys
        path: /.secrets
    secrets:
      - source: REACT_APP_GOOGLE_CLIENT_ID_STAGING
        target: REACT_APP_GOOGLE_CLIENT_ID
    environment:
      REACT_APP_API_BASE_URL: "https://backend.tilde.umuzi.org"
      REACT_APP_FEATURE_AUTHENTICATION: 1
      REACT_APP_FEATURE_BACKEND_API_ON: 1
      GCLOUD_SERVICE_ACCOUNT_NAME: "drone-io-deploy@umuzi-prod.iam.gserviceaccount.com"

    commands:
      - ls /.secrets
      - ls ./
      - gcloud auth activate-service-account $${GCLOUD_SERVICE_ACCOUNT_NAME} --key-file=/.secrets/gcloud-service-key.json
      - cd frontend
      - yes | apt install nodejs npm
      - npm install
      - npm run build
      - gcloud app deploy --appyaml app-staging.yaml
    when:
      branches: [develop, hotfix/*]

volumes:
  - name: secret_keys
    host:
      path: "/.secrets"
