kind: pipeline
type: docker
name: default

steps:
  - name: frontend-deploy-staging
    image: google/cloud-sdk
    volumes:
      - name: secret_keys
        path: /secrets
      # - name: secret_keys2
      #   path: /secret_keys2
      # - name: dockersock
      #   path: /var/run/docker.sock
    secrets:
      - source: REACT_APP_GOOGLE_CLIENT_ID_STAGING
        target: REACT_APP_GOOGLE_CLIENT_ID
    environment:
      REACT_APP_API_BASE_URL: "https://backend.tilde.umuzi.org"
      REACT_APP_FEATURE_AUTHENTICATION: 1
      REACT_APP_FEATURE_BACKEND_API_ON: 1
      GCLOUD_SERVICE_ACCOUNT_NAME: "drone-io-deploy@umuzi-prod.iam.gserviceaccount.com"
      NVM_DIR: "/root/.nvm"
    commands:
      # - ls /secrets
      # - apk add -U curl bash ca-certificates openssl ncurses coreutils python2 make gcc g++ libgcc linux-headers grep util-linux binutils findutils
      # - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      # - yes | apt install nodejs npm
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - nvm install node
      - npm install
      - npm run build
      - gcloud auth activate-service-account $${GCLOUD_SERVICE_ACCOUNT_NAME} --key-file=/secrets/drone-service-account-key.json
      - yes | gcloud app deploy --appyaml app-staging.yaml
    when:
      branches: [develop, hotfix/*]

volumes:
  # - name: secret_keys
  #   host:
  #     path: /home/sheena/drone-ci-setup/composition/.secrets

  - name: secret_keys
    host:
      path: /home/sheena/.secrets

  # - name: dockersock
  #   host:
  #     path: /var/run/docker.sock
