pipeline:
  backend-unit-tests:
    image: python:3.7
    commands:
      - cd backend
      - pip install --upgrade pip
      - pip install -r requirements.txt
      # - python manage.py migrate
      - python manage.py test

  frontend-unit-tests:
    image: node:12
    commands:
      - cd frontend
      - npm install
      - npm test

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - "6543:5432"
