pipeline:
  backend-unit-tests:
    group: test
    image: python:3.7
    environment:
      TILDE_SQL_HOST: postgres
      TILDE_SQL_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      GIT_REAL_WEBHOOK_SECRET: supersecret
    commands:
      - cd backend
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python manage.py makemigrations
      - python manage.py test --failfast

  frontend-unit-tests:
    group: test
    image: node:12
    commands:
      - cd frontend
      - npm install
      - npm test

  frontend-deploy-staging:
    group: deploy-staging
    # image: node:12
    image: google/cloud-sdk:latest
    secrets:
      - source: REACT_APP_GOOGLE_CLIENT_ID_STAGING
        target: REACT_APP_GOOGLE_CLIENT_ID
    environment:
      - REACT_APP_API_BASE_URL: "https://backend.tilde.umuzi.org"
      - REACT_APP_FEATURE_AUTHENTICATION: 1
      - REACT_APP_FEATURE_BACKEND_API_ON: 1
    commands:
      - yes | apt install nodejs
      - cd frontend
      - npm install
      - npm run build
      - gcloud app deploy --appyaml app-staging.yaml

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=password
