pipeline:
  backend-unit-tests:
    group: test
    image: python:3.7
    environment:
      TILDE_SQL_HOST: postgres
      TILDE_SQL_PORT: 5432
      RABBITMQ_HOST: rabbitmq
    commands:
      # - sleep 15
      - cd backend
      - pip install --upgrade pip
      - pip install -r requirements.txt
      # - python manage.py migrate
      - python manage.py test --failfast

  frontend-unit-tests:
    group: test
    image: node:12
    commands:
      - cd frontend
      - npm install
      - npm test

  # frontend-deploy-prod:
  #   image: node:12
  #   commands:
  #     - cd frontend
  #     - ./deploy_prod.sh

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=password
    # ports:
    #   - "15672:15672"
    #   - "5672:5672"
